# This is the Fastfile configuration file for the Fastlane automation tool

default_platform(:ios)

platform :ios do
 desc "Install Fastlane"
 lane :install_fastlane do
    sh "gem install fastlane -NV"
  end
 desc "Run Unit tests"
 lane :run_unit_tests do
    scan(
      scheme: "PeopleApp",                # Use your app scheme
      devices: ["6184FB15-321E-49BC-9FF0-E7D4C091E633"],             # Specify the devices
      clean: true,                        # Clean the project before testing
      code_coverage: true,                # Enable code coverage
      configuration: "Debug",             # Use Debug configuration
      sdk: "iphonesimulator",             # Use iPhone simulator SDK
      fail_build: true,                   # Fail the build on test failure
      only_testing: ["PeopleAppTests"], 	# Specify the unit test target
      output_style: "raw" 
    )
  end
  desc "Run UI tests"
  lane :run_ui_tests do
    scan(
      scheme: "PeopleApp",                # Use your app scheme
      devices: ["6184FB15-321E-49BC-9FF0-E7D4C091E633"],             # Specify the devices
      clean: true,                        # Clean the project before testing
      code_coverage: true,                # Enable code coverage
      configuration: "Debug",             # Use Debug configuration
      sdk: "iphonesimulator",             # Use iPhone simulator SDK
      fail_build: true,                   # Fail the build on test failure
      only_testing: ["PeopleAppUITests"], # Specify the unit test target
      output_style: "raw" 
    )
  end
  desc "Run all tests"
  lane :run_all_tests do
    run_unit_tests
    run_ui_tests
  end
end
