# This is the Fastfile configuration file for the Fastlane automation tool

default_platform(:ios)

platform :ios do
 desc "Install Fastlane"
 lane :install_fastlane do
    sh "gem install fastlane -NV"
  end
 desc "Run Unit tests"
 lane :run_unit_tests do
  available_simulators = sh('xcrun simctl list devices').stdout
  selected_simulator = available_simulators.scan(/iPhone [0-9]+/).sample

  if selected_simulator.nil?
    UI.user_error!("No available simulators found.")
  else
    scan(
      scheme: "PeopleApp",                    # Replace with your app's scheme name
      devices: [selected_simulator],          # Use a randomly selected simulator
      clean: true,                            # Clean the project before testing
      code_coverage: true,                    # Enable code coverage
      configuration: "Debug",                 # Use Debug configuration
      sdk: "iphonesimulator",                 # Use iPhone simulator SDK
      fail_build: true,                       # Fail the build on test failure
      only_testing: ["PeopleAppTests"],       # Specify the unit test target
      output_style: "raw"
    )
  end
  end
  desc "Run UI tests"
  lane :run_ui_tests do
    available_simulators = sh('xcrun simctl list devices').stdout
    selected_simulator = available_simulators.scan(/iPhone [0-9]+/).sample

    if selected_simulator.nil?
      UI.user_error!("No available simulators found.")
    else
      scan(
        scheme: "PeopleApp",                    # Replace with your app's scheme name
        devices: [selected_simulator],          # Use a randomly selected simulator
        clean: true,                            # Clean the project before testing
        code_coverage: true,                    # Enable code coverage
        configuration: "Debug",                 # Use Debug configuration
        sdk: "iphonesimulator",                 # Use iPhone simulator SDK
        fail_build: true,                       # Fail the build on test failure
        only_testing: ["PeopleAppTests"],       # Specify the unit test target
        output_style: "raw"
      )
    end
  end
  desc "Run all tests"
  lane :run_all_tests do
    run_unit_tests
    run_ui_tests
  end
end
